### ISSUE TITLE
error msg with demo data

### ISSUE THREAD

**Issue by Xiaomingdu** [vsoch/TtoZ#2]
Hello,

Thanks for providing this handy tool to convert t map to z map. However, I have the following error messages when I tried to use it on demo data in example folder.

First, I have python 2.7.10. I installed the TtoZ by entering "pip install git+https://github.com/vsoch/TtoZ.git" . It showed installation successful. 

Then, I downloaded example folder which has "tfMRI_LANGUAGE_STORY.nii_tstat1.nii.gz"

Then, I ran " TtoZ tfMRI_LANGUAGE_STORY.nii_tstat1.nii.gz 484 --output_nii=z_score_map.nii" on XQuartz terminal. 

It gave me this error:
"
Lacking argument to option --output_nii=z_score_map.nii
Image Exception : #22 :: ERROR: Could not open image 484

An exception has been thrown
ERROR: Could not open image 484Trace: read_volume4DROI.

libc++abi.dylib: terminating with uncaught exception of type RBD_COMMON::BaseException
Abort trap: 6
"

I will appreciate if you have any suggestions on how to fix this. Thanks!

**Comment by vsoch** [comment]
In what you copy pasted under the youtube video, you did not use two dashes:

```
  TtoZ tfMRI_LANGUAGE_STORY.nii_tstat1.nii.gz 484 -output_nii=z_score_map.nii
```

but here you did. Could you first confirm that your output_nii argument had two dashes and not one?

```
  --output_nii
```

**Comment by vsoch** [comment]
There might be a bug with parsing the input options, I am taking a look now.

**Comment by vsoch** [comment]
@Xiaomingdu, reinstall the package, and give this a try:

```
  TtoZ --t_stat_map=t_stat_map.nii.gz --dof=484 --output_nii=z_score_map.nii
```

**Comment by Xiaomingdu** [comment]
Thank you very much. I will try it today.

**Comment by Xiaomingdu** [comment]
Hi Vanessa,

Sorry for bothering you again and this might be a silly question.

How to complete uninstall TtoZ, so I can reinstall it?

I tried to reinstall it directly and hope to overwrite the old version. It
gave me this message:

bash-3.2$ pip install git+https://github.com/vsoch/TtoZ.git
Collecting git+https://github.com/vsoch/TtoZ.git
  Cloning https://github.com/vsoch/TtoZ.git to
/var/folders/t8/0mlyt2091fng3zprmwnbccd80000gn/T/pip-UD8emJ-build
  Requirement already satisfied (use --upgrade to upgrade): TtoZ==0.1.0
from git+https://github.com/vsoch/TtoZ.git in
/usr/local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): numpy in
/usr/local/lib/python2.7/site-packages (from TtoZ==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): scipy in
/usr/local/lib/python2.7/site-packages (from TtoZ==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): nibabel in
/usr/local/lib/python2.7/site-packages (from TtoZ==0.1.0)

Another interesting thing is that when I type: which TtoZ in XQuartz, it
showed:

bash-3.2$ which TtoZ
/usr/local/fsl/bin/TtoZ

Does TtoZ be installed to fsl folder? or that is an ssl-version of TtoZ?

Thanks.

Xiaoming

**Comment by vsoch** [comment]
If you read the message, it will tell you to use the update flag:

```
   Requirement already satisfied (use --upgrade to upgrade): TtoZ==0.1.0
```

Which would look like this

```
  pip install TtoZ --upgrade
```

But to be sure, I would uninstall, and reinstall

```
  pip uninstall TtoZ
  pip install TtoZ
```

**Comment by Xiaomingdu** [comment]
Thanks Vanessa!

It works for me well now.

However, I figure out the previous problem might not cause by your program.
It might be that I installed FSL first and it has a build-in function has
the same name as yours (i.e., ttoz).

Each time I type ttoz from xterm, it called FSL ttoz.

Now I installed your program in a cleaned mac (without FSL) and it runs
well.

Thanks again for your help and prompt reply. I really appreciate!

Best regards,

Xiaoming

**Comment by vsoch** [comment]
Great, so glad it worked! Thanks for pointing out the bug in the install script. I definitely agree about the name - for now it seems appropriate that the differences in capitalization distinguish the scripts, but this can be revisited if there are other concerns. I'm going to close the issue... best of luck!
